### ISSUE TITLE
How did you patch DSDT.aml?

### ISSUE THREAD

**Issue by yussdev** [xXConcasXx/asus-n552vw-catalina#1]
Hello, Thanks for sharing you EFI
I've created this issue just for asking a question 
How did you patch DSDT.aml?
Could you share you patching list / patching guide?

**Comment by xXConcasXx** [comment]
Hi, this is the patch list:

•	battery_ASUS-N55SL
•	Rename GFX0 to IGPU
•	Fix Mutex with non-zero SyncLevel
•	HPET Fix
•	IRQ Fix
•	OS WIN 10
•	Patch Voodooi2c SKL (GPIO 47)
•	RTC Fix
•	6-series SKL USB (usb_prw_0x6d_xhc_skl)
•	PATCH ASUSSMC

Patching guide:

https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/
