### ISSUE TITLE
Working on N552VW - not4k* 

### ISSUE THREAD

**Issue by BrainlabDev** [xXConcasXx/asus-n552vw-catalina#2]
Hello, firstly I have asus n552vw laptop full hd not 4k  1920 * 1080 

Can I run on my laptop or do you have any suggestions for efi ?

Thanks, anyway.

**Comment by xXConcasXx** [comment]
Hi, hardware is definitely different, you may have problems with patches, try it and let me know if it works.

**Comment by BrainlabDev** [comment]
Here is my laptop specs:
I see your resulotion 4k but otherwise everything is same

1920 x 1080 Piksel Intel® Core™ i7 16 GB DDR4-SDRAM 1256 GB HDD+SSD NVIDIA® GeForce® GTX 960M 
Intel Core i7-6700HQ (2.6GHz, 6M Cache), 16GB DDR3, 1000GB HDD + 256GB SSD +256 GB SSD (deleted optic driver), Intel HD Graphics 530 + NVIDIA GeForce GTX 960M

**Comment by xXConcasXx** [comment]
What version of the BIOS do you have?

**Comment by BrainlabDev** [comment]
Bios 304 latest one
whats your bios features ex I have been disabled vt-d

**Comment by xXConcasXx** [comment]
I made this EFI for v300, with your version it's unlikely to work.
