### ISSUE TITLE
Can I ask you something about my Trackpad

### ISSUE THREAD

**Issue by Jasonsupreme** [xXConcasXx/asus-n552vw-catalina#3]
I've used your EFI files and it works perfectly except my trackpad.
I've convert the pin number from Windows,and it is same with your pin number(opened in isal)
windows BIOS device name : \_SB.PCI0.I2C1.ETPD
in IOACPIPlane 0x5f convers to pin number is 0x47
and patched in config ,the trackpad still not exsist in catalina,
however,it works perfectly even without the trackpad, thanks again.

**Comment by Jasonsupreme** [comment]
OH sorry ， it was caused of my BIOS setting, it works now  thanks

**Comment by xXConcasXx** [comment]
I’m happy for you, stay tuned for v3
