### ISSUE TITLE
something about alc255 

### ISSUE THREAD

**Issue by Jasonsupreme** [xXConcasXx/asus-n552vw-catalina#4]
first，  it happened rarely，this problem can be happened after reboot from windows or when you off the duty,and shut down the Macos, even the screen was black and all the indicate led on the asus notebook was killed,  after one hour, when you get home ,press the start button,  you will find the pc is still awake, and type the password,you will find the speaker doesn't work anymore, although it can be fixed by reboot,  but ,i have a good solution to solve this issue, here is the link:

https://github.com/hackintosh-stuff/ComboJack

I used this last year, and i think it was good, maybe this can help you to make the EFI better , thanks!

some bugs may be caused by this ,if you don't have this need, use it with caution.

**Comment by Jasonsupreme** [comment]
also, https://github.com/xzhih/one-key-hidpi
this can help us to open the HiDPI , when we use another 2K  or 4K display, 
However!!👍 when we start the macOS, a huge logo will appears on the screen for seconds before we type in the password.

**Comment by xXConcasXx** [comment]
Thanks for the reports, I will correct them in the next release
