### ISSUE TITLE
OMG！ I drived Intel(R) Dual Band Wireless-AC 7265 just now!

### ISSUE THREAD

**Issue by Jasonsupreme** [xXConcasXx/asus-n552vw-catalina#5]
i've been used the usb wifi all the time , however ,in this afternoon, i drive the origional wifi adapter , according to this,https://github.com/zxystd/itlwm and http://bbs.pcbeta.com/viewthread-1856465-1-2.html， it's amazing!!

**Comment by xXConcasXx** [comment]
I don't know the Chinese language and google translate not working, but I assume it's a kext to make Intel's wifi controller work, correct me if I'm wrong. If I'm not mistaken, do you know if it correctly supports handoffs, airport, etc.?

**Comment by Jasonsupreme** [comment]
it is still updating and not stable,so it was compiled by me,and not that good as I expected, 
tested: 
wifi  (set ssid and password in nvRAM)(not perfect though.)
bluetooth  (still have some bugs there)
airdrop: not work
handoff: neg

it is a great step in hackintosh, i believe in the intel wifi adapter will be driverd in mac.

And, I've changed my wifi controller with BCM94360CS2 just like you this afternoon, it's perfect now~
