### ISSUE TITLE
here is my opencore can you try it?

### ISSUE THREAD

**Issue by Jasonsupreme** [xXConcasXx/asus-n552vw-catalina#6]

**Comment by Jasonsupreme** [comment]
[15.5.5 OC.zip](https://github.com/xXConcasXx/asus-n552vw-catalina/files/4716664/15.5.5.OC.zip)
this one can get into the system, however the elan and the backlight can't be setted.

**Comment by Jasonsupreme** [comment]
[opencore-0.58-no touchpad&backlight.zip](https://github.com/xXConcasXx/asus-n552vw-catalina/files/4717303/opencore-0.58-no.touchpad.backlight.zip)
only two probelms left now,1 no touchpad.    2 can't adjust the backlight of the screen,

![截屏2020-06-02 21 09 12](https://user-images.githubusercontent.com/29720066/83523839-53614000-a515-11ea-85b7-5236f7fe4d75.png)

**Comment by Jasonsupreme** [comment]
replace the config.plist with this one . 
all we have to do is to get the touchpad parameters well....

[config.plist.zip](https://github.com/xXConcasXx/asus-n552vw-catalina/files/4721454/config.plist.zip)

if you fix the touchpad , please let me know~~tks

**Comment by Jasonsupreme** [comment]
[opencore.zip](https://github.com/xXConcasXx/asus-n552vw-catalina/files/4724773/opencore.zip)
no touchpad, backlight can be adjusted now.

**Comment by Jasonsupreme** [comment]
[config.plist.zip](https://github.com/xXConcasXx/asus-n552vw-catalina/files/4729630/config.plist.zip)

using this config,and add the dadt.aml of your file in CLOVER, I can adjust the brightness by fn+F5/6, however, it still can't drive the touchpad, if you see this ,could reply it for me ?  
Q: dsdt.aml + ssdt_elan.aml   voodooi2c.kext+voodooi2celan.kext.    these 4 files to drive the touchpad right ?

**Comment by xXConcasXx** [comment]
Hey, send me email here: concas.luca997@live.it

**Comment by modaifallah** [comment]
where is the final file?

**Comment by xXConcasXx** [comment]
For the moment the opencore version is under development (@Jasonsupreme is collaborating with me), for the moment use the clover version which is the only stable one.

PS: A new EFI update will be released soon.
