### ISSUE TITLE
Internal speakers not working

### ISSUE THREAD

**Issue by ioantsaf** [xXConcasXx/asus-n552vw-catalina#7]
I have a N552VW FHD, BIOS v300.

Your EFI works almost flawlessly with Catalina 10.15.7, many thanks for that!

However I have one issue with the audio: Internal speakers do not work at all, although selected in the sound output options.
Only wired headphones work.

Yesterday, after some connection/disconnection attempts with my AirPods using a Belkin USB adapter (the connection only works if you unpair/repair the AirPods after they have been connected to another device), the audio started coming out of the internal speakers.

It survived some reboots, but after a kernel panic caused by the graphics driver (display was switched off but not sleeping, on AC), the internal speakers stopped working and I cannot get them to function again.

Could you point me to where the issue may lie? I also tried updating to the latest AppleALC version, but this stopped the internal speakers from appearing at all, so I reverted to your version.

**Comment by xXConcasXx** [comment]
This EFI is old, when I have time I upload a new version with improvements based on Opencore.

**Comment by ioantsaf** [comment]
> This EFI is old, when I have time I upload a new version with improvements based on Opencore.

Thanks, I will definitely donate for the new version!

**Comment by xXConcasXx** [comment]
Thanks a lot, I'm glad!😊
